### ISSUE TITLE
Not working!!!!

### ISSUE THREAD

**Issue by shandy4473** [jcsirot/ansible-plugin#1]
Having issues with getting ansible to work. 

Error:

ERROR: Build step failed with exception
java.lang.NullPointerException
    at org.jenkinsci.plugins.ansible.AbstractAnsibleInvocation.execute(AbstractAnsibleInvocation.java:178)
    at org.jenkinsci.plugins.ansible.AnsibleAdHocCommandInvocation.execute(AnsibleAdHocCommandInvocation.java:29)
    at org.jenkinsci.plugins.ansible.AnsibleAdHocCommandBuilder.perform(AnsibleAdHocCommandBuilder.java:114)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Build step 'Invoke Ansible Ad-Hoc Command' marked build as failure
Finished: FAILURE

**Comment by jcsirot** [comment]
Thanks I'm going to check. Can you also provide the version of the plugin and the details of the build step configuration.

**Comment by shandy4473** [comment]
Happy Holidays Jean-Christophe. I see you updated the plugin on 25th of December so I will uninstall the previous plugin and reinstall the updated ansible Jenkins plugin
