### ISSUE TITLE
works when used with UI but no with jenkinsfile.

### ISSUE THREAD

**Issue by princepaulson1** [jcsirot/ansible-plugin#22]
`14:11:42  <10.10.0.252> ESTABLISH SSH CONNECTION FOR USER: ****
14:11:42  <10.10.0.252> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/c6f39801c2 10.10.0.252 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:42  <10.10.0.253> ESTABLISH SSH CONNECTION FOR USER: ****
14:11:42  <10.10.0.253> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/ce5bf7554e 10.10.0.253 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:42  <10.10.0.252> ssh_retry: attempt: 1, caught exception([Errno 2] No such file or directory) from cmd (['ssh', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1230m', '-o', 'ServerAliveInterval=50', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User="****"', '-o', 'ConnectTimeout=60', '-o', 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=30m', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlPath=/tmp/.ansible/cp/c6f39801c2', '10.10.0.252', "/bin/sh -c 'echo ~**** && sleep 0'"]...), pausing for 0 seconds
14:11:42  <10.10.0.252> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/c6f39801c2 10.10.0.252 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:42  <10.10.0.254> ESTABLISH SSH CONNECTION FOR USER: ****
14:11:42  <10.10.0.254> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/706f9ebc62 10.10.0.254 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:42  <10.10.0.253> ssh_retry: attempt: 1, caught exception([Errno 2] No such file or directory) from cmd (['ssh', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1230m', '-o', 'ServerAliveInterval=50', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User="****"', '-o', 'ConnectTimeout=60', '-o', 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=30m', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlPath=/tmp/.ansible/cp/ce5bf7554e', '10.10.0.253', "/bin/sh -c 'echo ~**** && sleep 0'"]...), pausing for 0 seconds
14:11:42  <10.10.0.253> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/ce5bf7554e 10.10.0.253 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:42  <10.10.0.254> ssh_retry: attempt: 1, caught exception([Errno 2] No such file or directory) from cmd (['ssh', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1230m', '-o', 'ServerAliveInterval=50', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User="****"', '-o', 'ConnectTimeout=60', '-o', 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=30m', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlPath=/tmp/.ansible/cp/706f9ebc62', '10.10.0.254', "/bin/sh -c 'echo ~**** && sleep 0'"]...), pausing for 0 seconds
14:11:42  <10.10.0.252> ssh_retry: attempt: 2, caught exception([Errno 2] No such file or directory) from cmd (['ssh', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1230m', '-o', 'ServerAliveInterval=50', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User="****"', '-o', 'ConnectTimeout=60', '-o', 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=30m', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlPath=/tmp/.ansible/cp/c6f39801c2', '10.10.0.252', "/bin/sh -c 'echo ~**** && sleep 0'"]...), pausing for 1 seconds
14:11:42  <10.10.0.254> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/706f9ebc62 10.10.0.254 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:42  <10.10.0.253> ssh_retry: attempt: 2, caught exception([Errno 2] No such file or directory) from cmd (['ssh', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1230m', '-o', 'ServerAliveInterval=50', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User="****"', '-o', 'ConnectTimeout=60', '-o', 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=30m', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlPath=/tmp/.ansible/cp/ce5bf7554e', '10.10.0.253', "/bin/sh -c 'echo ~**** && sleep 0'"]...), pausing for 1 seconds
14:11:42  <10.10.0.254> ssh_retry: attempt: 2, caught exception([Errno 2] No such file or directory) from cmd (['ssh', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1230m', '-o', 'ServerAliveInterval=50', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User="****"', '-o', 'ConnectTimeout=60', '-o', 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=30m', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlPath=/tmp/.ansible/cp/706f9ebc62', '10.10.0.254', "/bin/sh -c 'echo ~**** && sleep 0'"]...), pausing for 1 seconds
14:11:43  <10.10.0.252> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/c6f39801c2 10.10.0.252 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:43  <10.10.0.253> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/ce5bf7554e 10.10.0.253 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:43  <10.10.0.254> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/706f9ebc62 10.10.0.254 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:43  <10.10.0.252> ssh_retry: attempt: 3, caught exception([Errno 2] No such file or directory) from cmd (['ssh', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1230m', '-o', 'ServerAliveInterval=50', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User="****"', '-o', 'ConnectTimeout=60', '-o', 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=30m', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlPath=/tmp/.ansible/cp/c6f39801c2', '10.10.0.252', "/bin/sh -c 'echo ~**** && sleep 0'"]...), pausing for 3 seconds
14:11:43  <10.10.0.253> ssh_retry: attempt: 3, caught exception([Errno 2] No such file or directory) from cmd (['ssh', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1230m', '-o', 'ServerAliveInterval=50', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User="****"', '-o', 'ConnectTimeout=60', '-o', 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=30m', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlPath=/tmp/.ansible/cp/ce5bf7554e', '10.10.0.253', "/bin/sh -c 'echo ~**** && sleep 0'"]...), pausing for 3 seconds
14:11:43  <10.10.0.254> ssh_retry: attempt: 3, caught exception([Errno 2] No such file or directory) from cmd (['ssh', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1230m', '-o', 'ServerAliveInterval=50', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User="****"', '-o', 'ConnectTimeout=60', '-o', 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem', '-C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=30m', '-o', 'StrictHostKeyChecking=no', '-o', 'ControlPath=/tmp/.ansible/cp/706f9ebc62', '10.10.0.254', "/bin/sh -c 'echo ~**** && sleep 0'"]...), pausing for 3 seconds
14:11:46  <10.10.0.252> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/c6f39801c2 10.10.0.252 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:46  <10.10.0.253> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/ce5bf7554e 10.10.0.253 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:46  <10.10.0.254> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=1230m -o ServerAliveInterval=50 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o 'IdentityFile="/home/enmstaging/staging01_cu_key.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="****"' -o ConnectTimeout=60 -o 'ProxyCommand=ssh -W %h:%p -q ****@10.2.10.10 -i /home/enmstaging/staging01_cu_key.pem' -C -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ControlPath=/tmp/.ansible/cp/706f9ebc62 10.10.0.254 '/bin/sh -c '"'"'echo ~**** && sleep 0'"'"''
14:11:46  The full traceback is:
14:11:46  Traceback (most recent call last):
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 145, in run
14:11:46      res = self._execute()
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 650, in _execute
14:11:46      result = self._handler.run(task_vars=variables)
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/gather_facts.py", line 66, in run
14:11:46      res = self._execute_module(module_name=fact_module, module_args=mod_args, task_vars=task_vars, wrap_async=False)
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 774, in _execute_module
14:11:46      self._make_tmp_path()
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 340, in _make_tmp_path
14:11:46      tmpdir = self._remote_expand_user(remote_tmp, sudoable=False)
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 658, in _remote_expand_user
14:11:46      data = self._low_level_execute_command(cmd, sudoable=False)
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 1062, in _low_level_execute_command
14:11:46      rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py", line 1189, in exec_command
14:11:46      (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py", line 392, in wrapped
14:11:46      return_tuple = func(self, *args, **kwargs)
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py", line 1050, in _run
14:11:46      return self._bare_run(cmd, in_data, sudoable=sudoable, checkrc=checkrc)
14:11:46    File "/usr/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py", line 800, in _bare_run
14:11:46      p = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
14:11:46    File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
14:11:46      errread, errwrite)
14:11:46    File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
14:11:46      raise child_exception
14:11:46  OSError: [Errno 2] No such file or directory
14:11:46  fatal: [10.10.0.252]: FAILED! => {
14:11:46      "msg": "Unexpected failure during module execution.", 
14:11:46      "stdout": ""`

**Comment by princepaulson1** [comment]
`  stages {
            stage( 'checkout src' ) {
                steps {
                    checkout scm

                    withCredentials([sshUserPrivateKey(credentialsId: 'stag', keyFileVariable: 'key',usernameVariable: 'username')]) {
                      ansiblePlaybook playbook: params.PLAYBOOKS, installation: '/usr/bin/ansible', inventory: params.INVENTORY, credentialsId: '${keyFileVariable}', extras: "-u ${username} -c ssh -vvv"
                    }

                    // ansiblePlaybook(playbook: params.PLAYBOOKS, credentialsId: 'stag', inventory: params.INVENTORY, extras: '-vvv -c ssh' )
                }
            }

         }`
